name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 coverage

      # Linting
      - name: Lint (flake8)
        run: |
          flake8 oc_lettings_site
      - name: Set Django settings module
        run:  |
          echo "DJANGO_SETTINGS_MODULE=oc_lettings_site.settings" >> $GITHUB_ENV
      # Tests + coverage
      - name: Run tests with coverage
        run: |
          coverage run --source="lettings,profiles,oc_lettings_site" -m pytest
          coverage report --fail-under=80
  build_and_push:
    needs: tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t thiveyasellar/oc-lettings-site:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push thiveyasellar/oc-lettings-site:${{ github.sha }}
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Update Render service image
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: srv-d4g6su24d50c73f8a27g
          IMAGE_TAG: ${{ github.sha }}
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"image\": {\"imagePath\": \"docker.io/thiveyasellar/oc-lettings-site:${IMAGE_TAG}\"}}" \
            https://api.render.com/v1/services/$SERVICE_ID

      - name: Trigger deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: srv-d4g6su24d50c73f8a27g
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            https://api.render.com/v1/services/$SERVICE_ID/deploys
